name: hershield
description: HerShield - Personal Safety App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Background and foreground service (compatible versions)
  flutter_background_service: ^5.0.0
  flutter_background_service_android: ^6.3.1
  flutter_background_service_ios: ^5.0.3

  # Microphone & speech recognition
  speech_to_text: ^7.3.0
  permission_handler: ^11.4.0

  # Location services
  geolocator: ^9.0.0

  # Phone call and SMS
  flutter_phone_direct_caller: ^2.0.1
  send_message: ^1.0.0  # Modern SMS plugin without namespace issues

  # Local storage
  shared_preferences: ^2.2.0

  # Notifications
  flutter_local_notifications: ^17.2.2

  # UI icons
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0

  # Shake detection
  shake: ^3.0.0

  # System overlay for floating assistant
  flutter_overlay_window: ^0.4.3

  # Contact picker
  flutter_contacts: ^1.1.7

  # Camera functionality
  camera: ^0.10.5+9
  path_provider: ^2.1.3
  path: ^1.9.0

  # File sharing
  share_plus: ^10.0.2

  # Bluetooth Low Energy (BLE) for smartwatch connectivity
  flutter_blue_plus: ^1.32.2
  flutter_reactive_ble: ^5.0.3

  # Google Fit integration
  health: ^12.0.0
  
  # Google Sign-In for authentication
  google_sign_in: ^6.2.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0

  # Network connectivity checking
  connectivity_plus: ^6.0.1

  # Mobile signal strength
  flutter_signal_strength: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
